CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  damage INT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  dungeon_id INT NOT NULL REFERENCES dungeons(id) ON DELETE CASCADE
);